apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-app
  name: service-config
  namespace: pipax-dev
data:
  APP_NAME: "service-app"
  APP_ENV: "production"
  APP_KEY: "app-service-key"
  APP_DEBUG: "false"
  APP_TIMEZONE: "UTC"
  APP_URL: "https://pipax-dev.com"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  LOG_CHANNEL: "stdout"
  ES_TYPE: "cloud"
  ES_PREFIX: "pipax-dev.service-app."
  ENQUEUE_MESSAGES_LIMIT: "100"
  ENQUEUE_TIME_LIMIT: "10"
  ENQUEUE_MEMORY_LIMIT: "50"

