apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-cronjob-import
  namespace: pipax-dev
spec:
  schedule: "0 2 * * *" #every day at 02:00
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: service-cronjob
            image: DOCKER_IMAGE_NAME
            envFrom:
            - secretRef:
                name: service-app-secret
            - configMapRef:
                name: service-app-config
            args:
            - /bin/sh
            - -c
            - "Some Command"
          restartPolicy: OnFailure

